// Angular/Angular-Essentials-Time-To-Practice/client/src/app/user-input/user-input.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-user-input',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './user-input.component.html',
  styleUrl: './user-input.component.css',
})
export class UserInputComponent {
  @Output() calculate = new EventEmitter<{
    initialInvestment: number;
    annualInvestment: number;
    expectedReturn: number;
    duration: number;
  }>();

  enteredInitialInvestment = '0';
  enteredAnnualInvestment = '0';
  enteredExpectedReturn = '5';
  enteredDuration = '10';

  onSubmit() {
    this.calculate.emit({
      annualInvestment: Number(this.enteredAnnualInvestment),
      duration: Number(this.enteredDuration),
      expectedReturn: Number(this.enteredExpectedReturn),
      initialInvestment: Number(this.enteredInitialInvestment),
    });
  }
}

<form (ngSubmit)="onSubmit()">
  <div class="input-group">
    <p>
      <label for="initial-investment">Initial Investment</label>
      <input
        id="initial-investment"
        name="initial-investment"
        type="number"
        [(ngModel)]="enteredInitialInvestment"
      />
    </p>
    <p>
      <label for="anual-initial-investment">Annual Investment</label>
      <input
        id="annual-initial-investment"
        name="annual-initial-investment"
        type="number"
        [(ngModel)]="enteredAnnualInvestment"
      />
    </p>
  </div>
  <div class="input-group">
    <p>
      <label for="expected-return">Expected Return</label>
      <input
        id="expected-return"
        name="expected-return"
        type="number"
        [(ngModel)]="enteredExpectedReturn"
      />
    </p>
    <p>
      <label for="duration">Duration</label>
      <input
        id="duration"
        name="duration"
        type="number"
        [(ngModel)]="enteredDuration"
      />
    </p>
  </div>

  <p>
    <button>Calculate</button>
  </p>
</form>

// React/React-Essentials-Practice-Project/client/src/components/UserInput/UserInput.jsx
export default function UserInput({ onChange, userInput }) {
    return (
        <section id="user-input">
            <div className="input-group">
                <p>
                    <label>Initial Investment</label>
                    <input
                        type="number"
                        required
                        value={userInput.initialInvestment}
                        onChange={(e) =>
                            onChange('initialInvestment', e.target.value)
                        }
                    />
                </p>
                <p>
                    <label>Annual Investment</label>
                    <input
                        type="number"
                        required
                        value={userInput.annualInvestment}
                        onChange={(e) =>
                            onChange('annualInvestment', e.target.value)
                        }
                    />
                </p>
            </div>
            <div className="input-group">
                <p>
                    <label>Expected Return</label>
                    <input
                        type="number"
                        required
                        value={userInput.expectedReturn}
                        onChange={(e) =>
                            onChange('expectedReturn', e.target.value)
                        }
                    />
                </p>
                <p>
                    <label>Duration</label>
                    <input
                        type="number"
                        required
                        value={userInput.duration}
                        onChange={(e) => onChange('duration', e.target.value)}
                    />
                </p>
            </div>
        </section>
    );
}
